name: Build APK

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Use the appropriate Node.js version

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova project
        run: |
          cordova create my-app
          cd my-app
          cordova platform add android

      - name: Copy HTML files
        run: |
          cp -r ../*.html my-app/www/
          cp -r ../css my-app/www/  # If you have a CSS folder
          cp -r ../js my-app/www/   # If you have a JS folder

      - name: Build APK
        run: |
          cd my-app
          cordova build android --release

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: my-app/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
